package com.myspace.example4;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Resumo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Information")
	private com.myspace.example4.Informations information;

	public Resumo() {
	}

	public com.myspace.example4.Informations getInformation() {
		return this.information;
	}

	public void setInformation(com.myspace.example4.Informations information) {
		this.information = information;
	}

	public Resumo(com.myspace.example4.Informations information) {
		this.information = information;
	}

}