package com.myspace.example1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class git_hook implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String abc;

	private java.lang.Integer def;

	private java.lang.Integer ghi;

	public git_hook() {
	}

	public java.lang.String getAbc() {
		return this.abc;
	}

	public void setAbc(java.lang.String abc) {
		this.abc = abc;
	}

	public java.lang.Integer getDef() {
		return this.def;
	}

	public void setDef(java.lang.Integer def) {
		this.def = def;
	}

	public java.lang.Integer getGhi() {
		return this.ghi;
	}

	public void setGhi(java.lang.Integer ghi) {
		this.ghi = ghi;
	}

	public git_hook(java.lang.String abc, java.lang.Integer def,
			java.lang.Integer ghi) {
		this.abc = abc;
		this.def = def;
		this.ghi = ghi;
	}

}