package com.myspace.example1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Input implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Nome")
	private java.lang.String nome;
	@org.kie.api.definition.type.Label(value = "Idade")
	private int idade;

	public Input() {
	}

	public java.lang.String getNome() {
		return this.nome;
	}

	public void setNome(java.lang.String nome) {
		this.nome = nome;
	}

	public int getIdade() {
		return this.idade;
	}

	public void setIdade(int idade) {
		this.idade = idade;
	}

	public Input(java.lang.String nome, int idade) {
		this.nome = nome;
		this.idade = idade;
	}

}