package com.myspace.example1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Resumo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Input")
	private com.myspace.example1.Input input;
	@org.kie.api.definition.type.Label(value = "Information")
	private com.myspace.example1.Informations information;

	public Resumo() {
	}

	public com.myspace.example1.Input getInput() {
		return this.input;
	}

	public void setInput(com.myspace.example1.Input input) {
		this.input = input;
	}

	public com.myspace.example1.Informations getInformation() {
		return this.information;
	}

	public void setInformation(com.myspace.example1.Informations information) {
		this.information = information;
	}

	public Resumo(com.myspace.example1.Input input,
			com.myspace.example1.Informations information) {
		this.input = input;
		this.information = information;
	}

}